export type SelfCollectItemType = {
  item_name: string;
  item_type: string;
  item_unit: string;
  item_qty: string;
  item_fu_qty: string;
  item_source: string;
  item_ef: string;
  item_ef_source: string;
  item_ef_source_ref: string;
  item_emission: null;
  transport_type: string;
  type1_gas: null;
  type1_gas_unit: null;
  type1_gas_qty: null;
  type1_ef: number | string;
  type1_ef_source: number;
  type2_distance: number;
  type2_outbound_load: string | number;
  type2_return_load: string | number;
  type2_vehicle: string;
  type2_outbound_load_percent: number;
  type2_return_load_percent: number;
  type2_outbound_ef: number;
  type2_return_ef: number;
  type2_ef_source: string;
  type2_ef_source_ref: string;
  transport_emission: number;
  total_emission: number;
  proportion: number;
  ratio: number;
  cut_off: number;
  add_on_detail: string;
  created_date?: string;
  updated_date?: string;
};

export type SelfCollectType = {
  company_id: number;
  product_id: number;
  self_collect_id?: number;
  self_collect_name: string;
  self_collect_ef: string;
  ratio: number;
  created_date?: string;
  updated_date?: string;
  input: SelfCollectItemType[];
  output: SelfCollectItemType[];
};
